//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Tour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LTTour
    {
        public Nullable<System.TimeSpan> GioBD { get; set; }
        public Nullable<System.TimeSpan> GioKT { get; set; }
        public string HoatDong { get; set; }
        public string Anh { get; set; }
        public int Ngay { get; set; }
        public string MaTour { get; set; }
    
        public virtual LT_Tour LT_Tour { get; set; }
    }
}
