//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Tour.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CNPMEntities : DbContext
    {
        public CNPMEntities()
            : base("name=CNPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiKH> LoaiKHs { get; set; }
        public virtual DbSet<LT_Tour> LT_Tour { get; set; }
        public virtual DbSet<NgonNgu> NgonNgus { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PacketTour> PacketTours { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<PhieuDC> PhieuDCs { get; set; }
        public virtual DbSet<PhuongThucThanhToan> PhuongThucThanhToans { get; set; }
        public virtual DbSet<TKTT> TKTTs { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<CT_LTTour> CT_LTTour { get; set; }
        public virtual DbSet<NgayBan> NgayBans { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<UserPoint> UserPoints { get; set; }
    }
}
