//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Tour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDC
    {
        public string MaDC { get; set; }
        public System.DateTime Ngaythamquan { get; set; }
        public string TenKH { get; set; }
        public string SDTKH { get; set; }
        public string EmailKH { get; set; }
        public string YCThem { get; set; }
        public string PickUp { get; set; }
        public int Invoice { get; set; }
        public int Paid { get; set; }
        public int SLAdult { get; set; }
        public int SLChild { get; set; }
        public System.DateTime NgayDatCho { get; set; }
        public string MaKH { get; set; }
        public string MaPT { get; set; }
        public string MaPTTT { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PacketTour PacketTour { get; set; }
        public virtual PhuongThucThanhToan PhuongThucThanhToan { get; set; }
    }
}
