//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Tour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKTT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TKTT()
        {
            this.PacketTours = new HashSet<PacketTour>();
        }
    
        public string STK_NH { get; set; }
        public string TenNH { get; set; }
        public string MaDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacketTour> PacketTours { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
