//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Tour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKTT
    {
        public string STK_NH { get; set; }
        public string TenNH { get; set; }
        public string MaDT { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
