//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Tour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPoint
    {
        public string MaKH { get; set; }
        public Nullable<int> SLXu { get; set; }
        public Nullable<System.DateTime> ActiDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public int expState { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
